name: Auto Migrate

on:
  schedule:
    # 每天 12 点执行 (UTC时间，北京时间 21 点)
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set timezone to Asia/Shanghai
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          echo "Asia/Shanghai" | sudo tee /etc/timezone
          date

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Clone lindexi.git repo
        run: |
          git clone https://github.com/lindexi/lindexi.git ../lindexi

      - name: Clone lindexi.github.io.git repo
        run: |
          git clone https://github.com/lindexi/lindexi.github.io.git ../lindexi.github.io

      - name: Yarn install
        run: |
          yarn install

      - name: Auto Migrate
        run: |
          yarn migrate

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated migration on $(date '+%Y-%m-%d %H:%M:%S') by GitHub Actions"
          git push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
